name: Documentation Update Validation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'pocketflow_agent/**'
      - 'scripts/**'
      - 'tests/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'pocketflow_agent/**'
      - 'scripts/**'
      - 'tests/**'
  workflow_dispatch:

jobs:
  test:
    name: Test PocketFlow
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install httpx pytest pytest-cov
      
      - name: Run tests
        run: |
          pytest tests/test_pocketflow.py -v --cov=pocketflow_agent
      
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: htmlcov/
  
  validate-docs:
    name: Validate Documentation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run documentation validation
        run: npm run docs:review
      
      - name: Generate dashboard
        run: npm run dashboard:generate
      
      - name: Upload dashboard
        uses: actions/upload-artifact@v3
        with:
          name: dashboard
          path: docs/dashboard.html
  
  update-badges:
    name: Update Status Badges
    runs-on: ubuntu-latest
    needs: [test, validate-docs]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Update badges
        run: npm run badges:update
      
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update status badges [skip ci]"
          file_pattern: README.md
