name: Documentation Validation

on:
  push:
    paths:
      - 'docs/**'
      - '**/*.md'
  pull_request:
    paths:
      - 'docs/**'
      - '**/*.md'

jobs:
  validate-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install -g markdownlint-cli
        
      - name: Lint Markdown files
        run: markdownlint 'docs/**/*.md' 'README.md'
        
      - name: Check for broken links
        run: |
          npm install -g markdown-link-check
          find docs -name "*.md" -exec markdown-link-check {} \;
          
  generate-docs-site:
    runs-on: ubuntu-latest
    needs: validate-markdown
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install -g docsify-cli
        
      - name: Generate documentation site
        run: |
          mkdir -p docs-site
          cp -r docs/* docs-site/
          echo '<!DOCTYPE html>
          <html>
          <head>
            <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
            <meta name="viewport" content="width=device-width,initial-scale=1">
            <meta charset="UTF-8">
            <title>Design Doc Automator - Documentation</title>
            <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/docsify@4/themes/vue.css">
          </head>
          <body>
            <div id="app"></div>
            <script>
              window.$docsify = {
                name: "Design Doc Automator",
                repo: "https://github.com/Creativityliberty/Docrequirementsautomator",
                loadSidebar: true,
                subMaxLevel: 3,
                auto2top: true,
              };
            </script>
            <script src="//cdn.jsdelivr.net/npm/docsify@4"></script>
            <script src="//cdn.jsdelivr.net/npm/prismjs@1/components/prism-bash.min.js"></script>
            <script src="//cdn.jsdelivr.net/npm/prismjs@1/components/prism-javascript.min.js"></script>
            <script src="//cdn.jsdelivr.net/npm/docsify-copy-code"></script>
            <script src="//cdn.jsdelivr.net/npm/docsify/lib/plugins/search.min.js"></script>
          </body>
          </html>' > docs-site/index.html
          echo '* [Accueil](/)
          * [Exigences](requirements.md)
          * [Conception](design.md)
          * [Tâches](tasks.md)
          * [Journal DM](dm-log.md)' > docs-site/_sidebar.md
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs-site
